server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        #enabled=true
        #host=localhost
        #port=8125
spring:
  application:
    name: @project.name@
info:
  version: @project.version@
  stage: dev
